language: python
python:
  # - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run test
script:
  - python -m pytest
notification:
  email: false
