language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run test
script:
  - python -m pytest
