language: python
python:
  - "3.5"
  # - "3.6"
  # - "nightly"
# command to install dependencies
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
  - pip install .
# command to run test
script:
  - pytest
